### ISSUE TITLE
Appling limitTo in ng-repeat causes undefined sort order

### ISSUE THREAD

**Issue by yoihito** [mattiash/angular-tablesort#11]
So i would like to limit number of displayed rows, but limitTo doesn't work. It is applied before angular-tablesort sorts the table.

example of ng-repeat
person in people_data | search:query | limitTo:limitSize

i think it might be problem with regexp

**Comment by mattiash** [comment]
I just noticed that my previous comment was badly formatted and the tr-tag in the example was not shown. I have updated the comment, I hope it makes more sense now.

**Comment by yoihito** [comment]
So thank you, i didn't notice this example too. It has more sense right now.

**Comment by yoihito** [comment]
Maybe it would be much easier to replace filter right in the ng-repeat.

```
<tr ng-repeat="person in people_data | search:query | tablesort | limitTo: 10">
```

this would be converted into that

```
<tr ng-repeat="person in people_data | search:query | tablesortOrderBy:sortFun | limitTo: 10">
```

**Comment by mattiash** [comment]
@yoihito yes, that looks fairly elegant.

**Comment by mattiash** [comment]
I would prefer if we retain backwards compatibility, i.e. if repeatExpr doesn't contain "tablesort", fallback to the old replacement regexp.

**Comment by mattiash** [comment]
Merged patches by yoihito that solves this issue.
