### ISSUE TITLE
Sorting by a computed value

### ISSUE THREAD

**Issue by aarmora** [mattiash/angular-tablesort#14]
Love the tablesorter!  This is really good work and I really appreciate it!

Maybe this is my inexperience with angular but is there a good way to sort by a computed value?  For example I have a column that uses one of two dates depending on which is more recent.  

    <table class="table table-striped" ts-wrapper>
            <thead>
                <tr>
                    <th ts-criteria="lastContact" ts-default>Last Contacted</th>
                    <th>Followup</th>
                    <th ts-criteria="Notes">Notes</th>
                </tr>
            </thead>
            <tbody>
                <tr ng-repeat="customer in customers" ts-repeat>
                    <td>{{lastContacted(customer)  | date}}</td>
                    <td><input class="form-control hiddenInput" type="date" ng-model="customer.Followup" ng-change="changeFollowup(customer, $index)" /></td>
                    <td><span class="fa" ng-class="customer.Notes ? 'fa-comments': 'fa-comment-o'" ng-click="openNotes(customer)"></span></td>
                </tr>
            </tbody>
        </table>

So...is there a great way to sort by the value that comes of my lastContact(customer)?  Thanks again!

**Comment by mattiash** [comment]
It is possible to sort by Angular expression https://docs.angularjs.org/guide/expression, but these are very limited. Another option is to store the computed value in the scope. This is probably more efficient anyway, since it would be very expensive for angular to watch the output from your function to decide if it needs to re-order the table.

**Comment by mattiash** [comment]
Closed due to inactivity
