### ISSUE TITLE
sorting values that can be "null" produces not stable sort.

### ISSUE THREAD

**Issue by dnozay** [mattiash/angular-tablesort#22]
Maybe `null` should be treated the same as `undefined` when sorting elements.

https://github.com/mattiash/angular-tablesort/blob/8282111ed4e6d607fd4606638074bb94056dae37/js/angular-tablesort.js#L111-L116

workaround: custom filter:
```
tableSortModule.filter( 'handleNull', function(){
    return function(input) {
        return input || '';
    };
} );
```

**Comment by gerardp** [comment]
I have the same problem !!
