### ISSUE TITLE
Is there a method for specifying to show or not the 'No data' row without tunning the CSS standard configuration?

### ISSUE THREAD

**Issue by felix-hurtado** [mattiash/angular-tablesort#23]
Please if not implemented to considerate it as a new feature, thanks

**Comment by gerardp** [comment]
+1

**Comment by mattiash** [comment]
In my opinion, empty tables look like an error occured. Therefore, I always want the "No data" row. I have no intention of implementing this enhancement request, but I am open to patches.

**Comment by pajaroblanco** [comment]
An option to not include the extra "No data" row would be helpful. We use CSS to style odd/even rows and depending on whether or not we make the table sortable changes the appearance of the table. When the table has no rows we hide the table completely and show a different DOM element.

**Comment by brandonbird** [comment]
An easy way to work around the "No data" row is to just add 
```.showIfLast {
	display: none;
}```
to your css to override the style and prevent the row from displaying.

**Comment by pajaroblanco** [comment]
Yes but the DOM element still exists and so is counted for even odd styling rules. We could just swap the even odd rules but then the appearance changes for tables that aren't sortable.

**Comment by brandonbird** [comment]
@pajaroblanco You're right, that wasn't ideal. I just submitted a PR that adds an option to disable the No data row. We'll see what @mattiash thinks about it :)

**Comment by mattiash** [comment]
Patch applied. Thank you!
