### ISSUE TITLE
Creating a seperate button/trigger to sort each column

### ISSUE THREAD

**Issue by shawkenator** [mattiash/angular-tablesort#24]
Do you have any suggestion on how to trigger the same sorting, using a button separate from the table, as you would by clicking on the table headers? I didn't see anything similar in the demo.

**Comment by mattiash** [comment]
You can add buttons with ts-criteria attributes outside the table. Just make sure to put the ts-wrapper attribute on a tag that surrounds both the table and the buttons. See this plunkr for an example:

http://plnkr.co/edit/WyvnAgUR4DprxFE7fb7n?p=preview

**Comment by shawkenator** [comment]
Thanks Mattiash, this is great. One more question? Is there a way to get this button sort in reverse first?

**Comment by mattiash** [comment]
For numeric fields, you can sort on "-field", i.e. the negative value of the field. For string fields there is no such trick that I can think of.
