### ISSUE TITLE
Reverse Sorting Issues in Chrome

### ISSUE THREAD

**Issue by shawkenator** [mattiash/angular-tablesort#25]
Hey Mattiash,

I came a crossed another small bug and was wondering if I can get your opinion on it. I am using this directive for a fairly complex table and I needed to create additional filter buttons, so I added an angular OrderBy property to the ng-repeat, on top of the ts-repeat code that's already there for the directive.  

Example code:
"< tr ng-repeat="parameter in parameters.response | orderBy:'Value':true | filter:paramquery" ts-repeat >"

This works perfectly in every browser except for Chrome. And chrome will render the results correctly if reverse=false, but once I try to sort with reverse=true, the sort order gets all mixed up.  So for a test I removed the ts-repeat line from the code above and the sorting issue was fixed (though it broke the directive, I at least figured out what my issue was). That my new orderBy property is conflicting with the angular-tablesort directive in some way.  

Do you have any suggestions on how to fix this? Is there a built-in orderBy variable in the directive that I should target instead of creating a new one?

Thanks again for all your help,
Steve

**Comment by mattiash** [comment]
Can you explain why you added the orderBy part of the filter? It will reorder the items in the array, but then tablesorter will reorder them again later in the filter.

**Comment by shawkenator** [comment]
Yeah, it's because of the additional sort buttons are little more complex than the table headers sorts. One example of the sorting buttons I need implemented says "Bring X to the top", now the value of X is coming through the service request, but isn't listed in as a table column.  And to make it even more challenging, to sort the objects that contain this X value to the top, I have to do it in reverse. And if I use a ts-criteria, the user would have to hit the button twice in order to achieve the desired sort. I asked on an earlier ticket, if I can start sorting in reverse and I believe you said the answer was no.

**Comment by mattiash** [comment]
But how can the orderBy statement have any effect at all? What ts-repeat does is that it effectively adds an extra orderBy clause to the end of the ng-repeat expression. The ng-repeat expression is a pipeline where parameters.response generates an array, orderBy rearranges the items in the array in a different order, filter:paramquery removes some entries from the array and then finally the orderBy added angular-tablesort reorders the items again. This means that the operation done by your orderBy filter is nullified by the orderBy added by angular-tablesort.

angular-tablesort can only sort by simple fields, it cannot take a sorting function. I think you are trying to do too much with angular-tablesort and you probably have to write your own custom tablesort routines.
