### ISSUE TITLE
Duplicate tr with empty td added to table

### ISSUE THREAD

**Issue by maljones** [mattiash/angular-tablesort#26]
Adding ts-repeat to the <tr> with ng-repeat resulted in a duplicate <tr> being generated. The duplicate <tr> generated an empty td with a colspan inside of it as well. 

It's odd enough that I wanted to bring it up.

**Comment by mattiash** [comment]
Tablesorter always adds a seemingly empty tr that is styled with css to only be shown when the table is empty. Look at the description and sample at 
http://mattiash.github.io/angular-tablesort/

If that is what you are seeing it's a feature, not a bug. 

/Mattias

**Comment by maljones** [comment]
Thanks Mattais. I totally missed that in the description when I was working
last night. I appreciate the quick response. I'll add the css in that's
necessary.

If it's only supposed to show if data is empty, it could be worth looking
into having the empty row show if the angular call of item as items returns
zero?

Thanks again!


--

Mal Jones
www.rocketkoi.com
We understand both space and scale!

**Comment by mattiash** [comment]
> If it's only supposed to show if data is empty, it could be worth looking
> into having the empty row show if the angular call of item as items returns
> zero?

I tried this but failed. Right now tablesorter only modifies the sorting expression for ng-repeat, it cannot affect the number of items in the list.

**Comment by maljones** [comment]
Thanks for giving it a try!

**Comment by jp555soul** [comment]
@maljones I'm actually getting the same output. Double TR data and extra empty TD. Ended up using CSS to hide the extra TD but how did you get your data to not duplicate?
