### ISSUE TITLE
CSS is not included in bower.json "main"

### ISSUE THREAD

**Issue by andersnorgaard** [mattiash/angular-tablesort#43]
Is this on purpose?

I use wiredep, and that looks for files to include in the "main" property - cf. https://github.com/taptapship/wiredep

Best regards,
Anders

**Comment by mattiash** [comment]
Yes, it is on purpose. I don't want to be responsible for how your tables look, since you probably have some sort of css-framework that you use for styling your page anyway. I regard the css-file as an example that you can build on.

**Comment by andersnorgaard** [comment]
Ah, ok. I was just surprised that the table was unstyled compared to the example. And even more surprised that the css-file was not included in bower.json. But you're right, I would need to override part of the styling anyway. Best regards, Anders
