### ISSUE TITLE
Poor performance with large resultset

### ISSUE THREAD

**Issue by sn0rcha** [mattiash/angular-tablesort#5]
I was wondering if anyone else was experiencing poor performance with large result sets with this module. If I have a table with over 5 or 6 columns and hundreds of rows, it slows to a crawl, and sometimes crashing the browser when re-sorting. I've tried using module "bindonce" in conjunction with this one, but it seems to have no effect. Is there anything I may have missed?

Great module btw tho!

Cheers,
Ben

**Comment by mattiash** [comment]
Closed due to inactivity
