### ISSUE TITLE
Tag 1.2 release

### ISSUE THREAD

**Issue by marcmascort** [mattiash/angular-tablesort#59]
Please, tag v1.2 release to use this version with bower.

Thanks and good job!

**Comment by logan-dunbar** [comment]
Yes please, the custom filter functionality is not available in the old 1.1.2 version. Thanks!!

**Comment by mattiash** [comment]
I have now released and tagged version 1.3.0.

**Comment by marcmascort** [comment]
Thanks!

**Comment by logan-dunbar** [comment]
Thanks! Can finally remove the only npm requirement for the front-end xD
