### ISSUE TITLE
Problems with angular-tablesort

### ISSUE THREAD

**Issue by morturus** [mattiash/angular-tablesort#60]
So i found you guys product and i think i found a great product.
The problem is: i can't use it.
Am I missing something?
I'm getting tabular data from a service which returns me a JSON.
I pass it to scope normally using my controller but angular-tablesort don't seems to work with it.
Here's my html
::
`<table class="table table-striped" ts-wrapper>
              <thead>
                <tr>
                  <th ts-criteria="X">X</th>
                  <th ts-criteria="PercentChange">PercentChange</th>
                  <th ts-criteria="Last">Last</th>
                  <th ts-criteria="Spread">Spread</th>
                </tr>
              </thead>
              <tbody>
                <tr ng-repeat="(key, value) in dados.data" ng-if="value.percentChange >= 0" ts-repeat>
    <td ><strong>{{key}}</strong></td>
    <td>{{value.percentChange}}</td>
    <td>{{value.last}}</td>
    <td>{{value.somecalchere- value.somecalcthere}}</td>
   </tr>
              </tbody>
            </table>`
::
and here's my module load:
`var app = angular.module('app', ['ui.bootstrap', 'tableSort']);`
::
::
::
I'm using
AngularJS v1.5.8
angular-tablesort last version
.
Tablesort seems work with dummy data.

**Comment by chrismbarr** [comment]
Your code sample is difficult to read... but from what I can tell it looks correct.  does `dados.data` contain all your data?

If you were to just make a regular table without the tablesort stuff, does that work?

```html
<table class="table table-striped">
  <thead>
    <tr>
      <th>X</th>
      <th>PercentChange</th>
      <th>Last</th>
      <th>Spread</th>
    </tr>
  </thead>
  <tbody>
    <tr ng-repeat="(key, value) in dados.data" ng-if="value.percentChange >= 0">
      <td><strong>{{key}}</strong></td>
      <td>{{value.percentChange}}</td>
      <td>{{value.last}}</td>
    <td>{{value.somecalchere- value.somecalcthere}}</td>
    </tr>
  </tbody>
</table>
```

get this to work first, and then add the tablesort stuff on top of it afterwards

**Comment by morturus** [comment]
Hey there, good night.

Yes! It does work
I also sent a friend and he said it's correct as well.
Sorry for code's format, i used code tag, i thought it'd work. :)

**Comment by morturus** [comment]
I managed to fix it by reordening my array, i was receiving a weird JSON from a webservice.
You guys could make it make a deep search in the future. Anyway, it's working now. Have a great day. Great software! Thanks!
