### ISSUE TITLE
angular-tablesort.d.ts is not a module

### ISSUE THREAD

**Issue by realph** [mattiash/angular-tablesort#62]
Getting this error when trying to build my project:

> Error TS2656: Exported external package typings file 'SOMEPATH/node_modules/angular-tablesort/typedefs/angular-tablesort.d.ts' is not a module. Please contact the package author to update the package definition.

**Comment by chrismbarr** [comment]
Perhaps we just need to change `declare namespace angular.tablesort` to `export module angular.tablesort` in the typedefs file here: https://github.com/mattiash/angular-tablesort/blob/master/typedefs/angular-tablesort.d.ts#L5

I'm not sure though, I'e not experienced this issue in my TS builds.

**Comment by chrismbarr** [comment]
@realph Check the PR that this issue is now linked to. I think this will solve your problem.

**Comment by chrismbarr** [comment]
@realph version 1.3.2 has now been released which includes this PR.  Please see if this fixes the issue

**Comment by mattiash** [comment]
Fix included in 1.3.2
