### ISSUE TITLE
How can I change sorting algorithm?

### ISSUE THREAD

**Issue by mattiasnordqvist** [mattiash/angular-tablesort#67]
Is is possible to change sorting algorithm. I need to override javascripts default sorting to handle some special cases.

**Comment by RopoMen** [comment]
Hi,

is `tableSortConfigProvider.filterFunction` what you are looking for? (see. readme)

or you can also use per table 
```html
<table ts-wrapper  ts-filter-function="customFilterFn">
```

**Comment by mattiasnordqvist** [comment]
filter doesn't sound like what I'm looking for. My problem is that the letters `å` and `ä` are sorted incorrectly in my Swedish application.

**Comment by mattiash** [comment]
I just merged PR #71 that uses Intl.Collator to sort strings. On second thought, I am however a bit uncertain if that patch is correct. But if it is correct, it ought to sort Swedish characters correctly if the user has a Swedish locale. Perhaps you could test that patch and see if it works for you?

**Comment by mattiasnordqvist** [comment]
I haven't looked into the code but it seems it solved my problem! :) thank you
