### ISSUE TITLE
Doesn't work with "ng-repeat-start" attribute

### ISSUE THREAD

**Issue by NameFILIP** [mattiash/angular-tablesort#7]
Sometimes, there are "ng-repeat-start" and "ng-repeat-end" attributes instead of the "ng-repeat"
https://docs.angularjs.org/api/ng/directive/ngRepeat
http://jsfiddle.net/NameFILIP/k66Za/37/

**Comment by brandonbird** [comment]
It took some effort to get it to work right (first time I've really messed with angular DOM compilation and multiElement directives), but I converted the ts-repeat directive into a multiElement directive that mirrors the ng-repeat-start/-end. In my PR you can add ```ts-repeat-start``` and ```ts-repeat-end``` to your respective ```ng-repeat-start``` & ```ng-repeat-end``` table rows and have it function as expected.

**Comment by mattiash** [comment]
Fixed by the commit from @brandonbird and released in v1.1.0
