### ISSUE TITLE
get the sorted data back from angular-tablesort

### ISSUE THREAD

**Issue by vannim152** [mattiash/angular-tablesort#74]
Hi, is there an easy way to get access to the sorted data by tablesort module? From my understanding, the module will make a copy of the original collection and manipulate that copy. If the module can also provide a way to getSortedData(), that will be awesome

**Comment by chrismbarr** [comment]
A need for this has come up for me as well, I'm going to begin looking for a way to get this data.  I'll submit a PR if needed.  We need to be able to use the filtered data for exporting to a CSV file.

In your opinion, what would be a good syntax for this?  I assume we'd want a way to make certain things optional, like sorting and paging.  For our use case we'd want the filtered data, but all of it and not just the current page of data.

**Comment by chrismbarr** [comment]
@vannim152 Check the PR that this issue now links to, I think this will add the needed functionality that we both want & need!
