### ISSUE TITLE
collator undefined?

### ISSUE THREAD

**Issue by RopoMen** [mattiash/angular-tablesort#79]
Hi,

I looked in to the new `createDefaultComparer()` and noticed that
```js
var collator = new Intl.Collator(undefined, { sensitivity: 'case' });
```
is created inside a scope of `createDefaultComparer()` function. This means that collator.compare used in [line 332](https://github.com/mattiash/angular-tablesort/blob/master/js/angular-tablesort.js#L332) should be undefined, am I right?
```js
compResult = collator.compare(aval, bval);
```

**Comment by mattiash** [comment]
You're right. Fix pushed. Thank you!
